spring.application.name=app

twilio.account.sid=1264735868893343
twilio.auth.token=EAAZALVnOwhKABR5R29scDvx6qiJOEw6d3iBJwceJKv2HOqY2XiYvuQsklPBZALyVgkXXLezRZBkfqZCdUJPFMjmLRhSQZB7zmUWn8YmJ09RVQO7002VqZCNUdUNJ69doUZAKfTWYQaGfZAs3ZCDc124RQ1UIZAFgSEbU2dGC9pg1VMtMJ9HZBSWuupuMfgtTkZC8Qeb1jSFpkMqmzVeDH39p678NZCvNoGfgmSlDJEZAfZAd64m7WuO94x3Nmg9HKWZCVZC9fCtugdCCK2woXV2KDbflEjZAsgxwZDZD
twilio.whatsapp.number=whatsapp:+1216945994830075

whatsapp.access-token=EAAZALVnOwhKABR92RTGvFmSHEVWFNZAKUEowZBnZA8wT9hQUYsNBes35B4Kz6xZBbLGFsHBbB7qw5lj43Yvw3eDAnuKGGxSZAFjmoFy1gPLO3dbiZCp8O5Efo5KJAAsWrWDTng0B6yKjUtyM3ZCZCeqjpNZA0QXaVGWAspx2iKpD2as9pKyC8jcbFXaIofWIriQt54f5QgWm8obsUYmtoI0W964LJMm4yfxjufyemK
whatsapp.phone-number-id=1216945994830075

chatboaturl=https://tartar-handsaw-paging.ngrok-free.dev/bot/reply


# own config

#whatsapp.access-token=EAAVok7Rh6NsBR93bT9pCQriHRZC4IkbWEtwBZAWEN2tjkReGjdfGVKcyaahH0fhAdgDjrT9YJWdBA3jNMnfbxPirGEGj5UQlmJ3U5WbZBtHKYbYvepRxV1KLwq6YXGgNtVY9HerM99AkOLrjt8rPaoZBcX8IYBZCHgAyto4ZAHysWqrR8SwumL7eGKanUSU4yYD56sEq9RMb1ZCFVDH5gMJUIsq8vbRDkcPSnmXd9v1ZA8XUgYnInDceZBGGaZABLnWHVZCDsZBz4snimFnW8Ixw00uNJwZDZD
#whatsapp.phone-number-id=1164663493401156
webhook.verify-token=3G8CxmBUsUjYzASV6fQlF5oUKCq_uftVw6yzJsK4ZFiNxXpN
webhook.verify.token=3G8CxmBUsUjYzASV6fQlF5oUKCq_uftVw6yzJsK4ZFiNxXpN
# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://147.93.19.155:5432/appdb
spring.datasource.username=postgres
spring.datasource.password=TRPinsider@1444
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp


logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG